# ─────────────────────────────
# 1. ベースイメージ
# ─────────────────────────────
FROM ruby:3.3.6

# ─────────────────────────────
# 2. 必要なパッケージ
# ─────────────────────────────
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends --fix-missing nodejs build-essential postgresql-client cron

# ─────────────────────────────
# 3. 作業ディレクトリ
# ─────────────────────────────
WORKDIR /app

# ─────────────────────────────
# 4. Gemインストール
# ─────────────────────────────
COPY Gemfile Gemfile.lock ./
RUN bundle install

# ─────────────────────────────
# 5. アプリケーションコード
# ─────────────────────────────
COPY . .

# ─────────────────────────────
# 6. cron設定スクリプト
# ─────────────────────────────
COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# ─────────────────────────────
# 7. ポート
# ─────────────────────────────
EXPOSE 3000

# ─────────────────────────────
# 8. Entrypoint
# ─────────────────────────────
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]